export const content = {
  brand: { name: "Habitar", mark: "h." },
  auth: {
    eyebrow: "BIENVENIDO A TU COMUNIDAD",
    headline: "Tu hogar va más allá de tu puerta.",
    description: "Un solo acceso para tu unidad, sin importar tu rol.",
    title: "Bienvenido de nuevo",
    subtitle: "Ingresa tus datos para acceder a tu unidad.",
    footer: "Espacios compartidos. Una vida más simple.",
    failed: "No se pudo iniciar sesión. Intenta nuevamente.",
    invalid: "El correo o la contraseña no son correctos.",
    loading: "Cargando…",
    redirecting: "Llevándote a tu espacio…",
    ssoFailed: "No se pudo completar el acceso. Intenta nuevamente.",
  },
  loginLabels: {
    email: "Correo electrónico",
    password: "Contraseña",
    showPassword: "Mostrar",
    hidePassword: "Ocultar",
    submit: "Iniciar sesión",
    pending: "Ingresando…",
  },
  recover: {
    eyebrow: "RECUPERAR ACCESO",
    headline: "Te ayudamos a volver a entrar.",
    description: "Te enviaremos instrucciones para restablecer tu contraseña.",
    title: "Recuperar contraseña",
    subtitle: "Ingresa el correo asociado a tu cuenta.",
    footer: "Espacios compartidos. Una vida más simple.",
    email: "Correo electrónico",
    submit: "Enviar instrucciones",
    pending: "Enviando…",
    sent: "Si el correo existe, vas a recibir instrucciones para continuar. Revisa tu bandeja de entrada.",
    backToLogin: "Volver al inicio de sesión",
  },
  confirm: {
    eyebrow: "RECUPERAR ACCESO",
    headline: "Elige tu nueva contraseña.",
    description: "El enlace que recibiste por correo es válido por tiempo limitado.",
    title: "Restablecer contraseña",
    subtitle: "Ingresa tu nueva contraseña para continuar.",
    footer: "Espacios compartidos. Una vida más simple.",
    newPassword: "Nueva contraseña",
    passwordPolicy: "Entre 8 y 72 caracteres, con al menos una minúscula, una mayúscula y un dígito.",
    showPassword: "Mostrar",
    hidePassword: "Ocultar",
    submit: "Restablecer contraseña",
    pending: "Guardando…",
    success: "Tu contraseña fue restablecida. Ya puedes iniciar sesión.",
    invalidToken: "El enlace no es válido o ya expiró. Solicita uno nuevo.",
    goToLogin: "Ir al inicio de sesión",
    tryAgain: "Solicitar un nuevo enlace",
  },
} as const;
